### ISSUE TITLE
Google Drive source fails indexing due to missing 'parents'

### ISSUE THREAD

**Issue by iderdik** [GerevAI/gerev#75]
The document in question was shared from another use's Drive (in case that matters).

```
2023-03-28 16:40:40,412 | INFO | google_drive.py:138 | processing file [redacted]
2023-03-28 16:40:41,468 | ERROR | base_data_source.py:120 | Error while indexing data source
Traceback (most recent call last):
  File "/app/data_source/api/base_data_source.py", line 118, in index
    self._feed_new_documents()
  File "/app/data_source/sources/google_drive/google_drive.py", line 105, in _feed_new_documents
    self._feed_drive(drive=drive)
  File "/app/data_source/sources/google_drive/google_drive.py", line 131, in _feed_drive
    self._feed_file(file)
  File "/app/data_source/sources/google_drive/google_drive.py", line 172, in _feed_file
    parent_name = self._get_parents_string(file)
  File "/app/data_source/sources/google_drive/google_drive.py", line 101, in _get_parents_string
    return self._get_parent_name(file['parents'][0]) if file['parents'] else ''
KeyError: 'parents'
```

**Comment by Roey7** [comment]
Fixed in 0.0.28, thanks! 🧦
